### ISSUE TITLE
Error: "object 'input' not found" when running Examples

### ISSUE THREAD

**Issue by omarun** [GregorDeCillia/shinyLikert#1]
I wanted to thank you for the great work you are doing to explore Likert.
I am writing to ask you to help me with a mistake I have when I try to execute your examples. Basically these are (R version 3.3.3):

```r
fluidPage( renderShinyLikert( 
   createTestData(),
   dropdown = "country" )
)
# Error: could not find function "fluidPage"

plot( renderShinyLikert( testData2 ) )  
# Error in get("input", envir = env) : object 'input' not found
```
  
thank you very much.

**Comment by GregorDeCillia** [comment]
Hello Omarun.

This package is designed to be used only within shiny apps or shiny-markdown-documents (RMarkdown-documents with `runtime: shiny` in the YAML header).
As far as I can tell, you tried to copy the lines of `examples/misc/Examples.Rmd` directly into the console which will not work.

Try running the `.Rmd` with 

```r
rmarkdown::run( "examples/misc/Examples.Rmd" )
```

instead. If you have `RStudio` installed, you can also run RMarkdown files using the ["Run Document" button](http://rmarkdown.rstudio.com/images/shiny-run-document.png).
